# example netlify.toml
[build]
  command = "react-scripts build && cp -R build netlify/functions && ls -al netlify/functions/build"
  functions = "netlify/functions"
  publish = "build"

  [[redirects]]
    from = "/*"
    to = "/.netlify/functions/index"
    status = 200

[functions]
  external_node_modules = ["express"]
  included_files = ["netlify/functions/build"]


  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
